name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
      - name: Build all services with docker-compose
        run: docker-compose -f docker-compose.yaml build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag backend image
        run: docker tag backend:latest mahendrakarvineethabai/crud-dd-task-mean-app-backend:latest

      - name: Tag frontend image
        run: docker tag frontend:latest mahendrakarvineethabai/crud-dd-task-mean-app-frontend:latest

      - name: Push backend image
        run: docker push mahendrakarvineethabai/crud-dd-task-mean-app-backend:latest

      - name: Push frontend image
        run: docker push mahendrakarvineethabai/crud-dd-task-mean-app-frontend:latest
        uses: docker/setup-buildx-action@v3

